export default (appsStore, defaultCrypto, defaultCryptoAmount) => ({
    "settings": {
        "hasHeaders": true,
        "constrainDragToContainer": false,
        "reorderEnabled": true,
        "selectionEnabled": false,
        "popoutWholeStack": false,
        "blockedPopoutsThrowError": true,
        "closePopoutsOnUnload": true,
        "showPopoutIcon": false,
        "showMaximiseIcon": true,
        "showCloseIcon": false,
        "responsiveMode": "onload",
        "tabOverlapAllowance": 0,
        "reorderOnTabMenuClick": true,
        "tabControlOffset": 10,
    },
    "dimensions": {
        "borderWidth": 5,
        "borderGrabWidth": 15,
        "minItemHeight": 10,
        "minItemWidth": 10,
        "headerHeight": 20,
        "dragProxyWidth": 300,
        "dragProxyHeight": 200,
    },
    "labels": {
        "close": "close",
        "maximise": `Pay-Per-Use: 1 App Store Credit (Or use App for FREE if you have more than [${defaultCryptoAmount} ${defaultCrypto}])`,
        "minimise": "minimise",
        "popout": "open in new window",
        "popin": "pop in",
        "tabDropdown": "additional tabs",
    },
    "content": [{
        "type": "column",
        "isClosable": true,
        "reorderEnabled": true,
        "title": "",
        "content": [{
            "type": "row",
            "isClosable": true,
            "reorderEnabled": true,
            "title": "",
            "height": 94.375,
            "content": [{
                    "type": "column",
                    "isClosable": true,
                    "reorderEnabled": true,
                    "title": "",
                    "width": 31.755044737922578,
                    "content": [{
                        "type": "stack",
                        "header": {},
                        "isClosable": true,
                        "reorderEnabled": true,
                        "title": "",
                        "activeItemIndex": 0,
                        "height": 50,
                        "width": 32.48459586806814,
                        "content": [{
                            "title": "Heatmap Coins",
                            "type": "component",
                            "component": "Iframe",
                            "props": {
                                "name": "Heatmap Coins",
                                "url": "https://bct-heatmaps.app.cgblockchain.com/map/last_day/all/cap",
                                "appId": "531b2793-c29c-4db3-89bf-36b7df11487d",
                                appsStore,
                            },
                            "componentState": {},
                            "componentName": "lm-react-component",
                            "isClosable": true,
                            "reorderEnabled": true,
                        }],
                    }, {
                        "type": "stack",
                        "header": {},
                        "isClosable": true,
                        "reorderEnabled": true,
                        "title": "",
                        "activeItemIndex": 0,
                        "height": 50,
                        "content": [{
                            "title": "Coin Price Chart",
                            "type": "component",
                            "component": "Iframe",
                            "props": {
                                "name": "Coin Price Chart",
                                "url": "https://bct-apps-sandbox.app.cgblockchain.com/cryptocurrency-price-chart/",
                                "appId": "1ebc19bb-ed58-4578-94ca-ba2f937cb791",
                                appsStore,
                            },
                            "componentState": {},
                            "componentName": "lm-react-component",
                            "isClosable": true,
                            "reorderEnabled": true,
                        }],
                    }],
            }, {
                "type": "column",
                "isClosable": true,
                "reorderEnabled": true,
                "title": "",
                "width": 34.80220826113909,
                "content": [{
                    "type": "stack",
                    "header": {},
                    "isClosable": true,
                    "reorderEnabled": true,
                    "title": "",
                    "activeItemIndex": 0,
                    "width": 34.831748970199236,
                    "height": 50,
                    "content": [{
                        "title": "Heatmap Exchanges",
                        "type": "component",
                        "component": "Iframe",
                        "props": {
                            "name": "Heatmap Exchanges",
                            "url": "https://bct-heatmaps.app.cgblockchain.com/exchanges",
                            "appId": "b60338f7-0f27-4f2d-b8f0-c44212e6fcda",
                            appsStore,
                        },
                        "componentState": {},
                        "componentName": "lm-react-component",
                        "isClosable": true,
                        "reorderEnabled": true,
                    }],
                }],
            },
            {
                "type": "column",
                "isClosable": true,
                "reorderEnabled": true,
                "title": "",
                "width": 33.44274700093835,
                "content": [{
                    "type": "stack",
                    "header": {},
                    "isClosable": true,
                    "reorderEnabled": true,
                    "title": "",
                    "activeItemIndex": 0,
                    "width": 32.683655161732624,
                    "height": 50,
                    "content": [{
                        "title": "Heatmap Unusual Volume",
                        "type": "component",
                        "component": "Iframe",
                        "props": {
                            "name": "Heatmap Unusual Volume",
                            "url": "https://bct-heatmaps.app.cgblockchain.com/map/unusual_volume/top100",
                            "appId": "33c0e244-e045-4daa-b438-747caa1ce935",
                            appsStore,
                        },
                        "componentState": {},
                        "componentName": "lm-react-component",
                        "isClosable": true,
                        "reorderEnabled": true,
                    }],
                }],
            }],
        }],
    }],
    "isClosable": true,
    "reorderEnabled": true,
    "title": "",
    "openPopouts": [],
    "maximisedItemId": null,
})
