export default (appsStore, defaultCrypto, defaultCryptoAmount) => ({
    settings: {
        hasHeaders: true,
        constrainDragToContainer: false,
        reorderEnabled: true,
        selectionEnabled: false,
        popoutWholeStack: false,
        blockedPopoutsThrowError: true,
        closePopoutsOnUnload: true,
        showPopoutIcon: false,
        showMaximiseIcon: true,
        showCloseIcon: false,
        responsiveMode: "onload",
        tabOverlapAllowance: 0,
        reorderOnTabMenuClick: true,
        tabControlOffset: 10,
    },
    dimensions: {
        borderWidth: 5,
        borderGrabWidth: 15,
        minItemHeight: 10,
        minItemWidth: 10,
        headerHeight: 20,
        dragProxyWidth: 300,
        dragProxyHeight: 200,
    },
    labels: {
        close: "close",
        maximise: `Pay-Per-Use: 1 App Store Credit (Or use App for FREE if you have more than [${defaultCryptoAmount} ${defaultCrypto}])`,
        minimise: "minimise",
        popout: "open in new window",
        popin: "pop in",
        tabDropdown: "additional tabs",
    },
    content: [{
        type: "column",
        isClosable: true,
        reorderEnabled: true,
        title: "",
        content: [{
            type: "row",
            isClosable: false,
            reorderEnabled: true,
            title: "",
            height: 94.375,
            content: [{
                    type: "column",
                    isClosable:  false,
                    reorderEnabled:  true,
                    title:  "",
                    width:  31.755044737922578,
                    content:  [{
                        type: "stack",
                        header:  {},
                        isClosable:  false,
                        reorderEnabled:  true,
                        title:  "",
                        activeItemIndex:  0,
                        height:  50,
                        width:  32.48459586806814,
                        content:  [{
                            title:  "Coins Selector",
                            type: "component",
                            component:  "Iframe",
                            props:  {
                                name:  "Coins Selector",
                                url:  "https://bct-coin-selector.app.cgblockchain.com",
                                appId:  "c3570d89-65c7-4750-8d81-7eefa7c9f633",
                                appsStore,
                            },
                            componentState:  {},
                            componentName:  "lm-react-component",
                            isClosable:  false,
                            reorderEnabled:  true,
                        }],
                    }, {
                        type: "stack",
                        header:  {},
                        isClosable:  false,
                        reorderEnabled:  true,
                        title:  "",
                        activeItemIndex:  0,
                        height:  50,
                        content:  [{
                            title:  "ICO Governance",
                            type: "component",
                            component:  "Iframe",
                            props:  {
                                name:  "ICO Governance",
                                url:  "https://ico-governance.app.cgblockchain.com/database",
                                appId:  "9f6480dc-043d-4d75-ab2d-d662fbec11aa",
                                appsStore,
                            },
                            componentState:  {},
                            componentName:  "lm-react-component",
                            isClosable:  false,
                            reorderEnabled:  true,
                        }],
                    }],
            }, {
                type: "column",
                isClosable:  false,
                reorderEnabled:  true,
                title:  "",
                width:  34.80220826113909,
                content:  [{
                    type: "stack",
                    header:  {},
                    isClosable:  true,
                    reorderEnabled:  true,
                    title:  "",
                    activeItemIndex:  0,
                    width:  34.831748970199236,
                    height:  50,
                    content:  [{
                        title:  "Top ICOs",
                        type: "component",
                        component:  "Iframe",
                        props:  {
                            name:  "Top ICOs",
                            url:  "https://bct-apps-sandbox.app.cgblockchain.com/top-ico/",
                            appId:  "608eb236-2771-4886-973e-39055e46a6de",
                            appsStore,
                        },
                        componentState:  {},
                        componentName:  "lm-react-component",
                        isClosable:  false,
                        reorderEnabled:  true,
                    }],
                }, {
                    type: "stack",
                    header:  {},
                    isClosable:  false,
                    reorderEnabled:  true,
                    title:  "",
                    activeItemIndex:  0,
                    height:  50,
                    content:  [{
                        title:  "ICOs Gantt Charts",
                        type: "component",
                        component:  "Iframe",
                        props:  {
                            name:  "ICOs Gantt Charts",
                            url:  "https://bct-chart-ico.app.cgblockchain.com/",
                            appId:  "75b3f8f1-0360-4af2-b740-32fd4c6c33da",
                            appsStore,
                        },
                        componentState:  {},
                        componentName:  "lm-react-component",
                        isClosable:  false,
                        reorderEnabled:  true,
                    }],
                }],
            },
            {
                type: "column",
                isClosable:  false,
                reorderEnabled:  true,
                title:  "",
                width:  33.44274700093835,
                content:  [/*{
                    type: "stack",
                    header:  {},
                    isClosable:  true,
                    reorderEnabled:  true,
                    title:  "",
                    activeItemIndex:  0,
                    width:  32.683655161732624,
                    height:  50,
                    content:  [{
                        title:  "ICO Directories",
                        type: "component",
                        component:  "Iframe",
                        props:  {
                            name:  "ICO Directories",
                            url:  "https://bct-directories.app.cgblockchain.com/?source=bct-consolidation.app",
                            appId:  "fb86b383-e9f7-4f5d-b8df-d1d410621384",
                            appsStore,
                        },
                        componentState:  {},
                        componentName:  "lm-react-component",
                        isClosable:  false,
                        reorderEnabled:  true,
                    }],
                },*/ {
                    type: "stack",
                    header:  {},
                    isClosable:  false,
                    reorderEnabled:  true,
                    title:  "",
                    activeItemIndex:  0,
                    height:  50,
                    content:  [{
                        title:  "ICOs List",
                        type: "component",
                        component:  "Iframe",
                        props:  {
                            name:  "ICOs List",
                            url:  "https://bct-chart-ico.app.cgblockchain.com/list",
                            appId:  "dafda12b-75df-4653-a976-3484394c0dd3",
                            appsStore,
                        },
                        componentState:  {},
                        componentName:  "lm-react-component",
                        isClosable:  false,
                        reorderEnabled:  true,
                    }],
                }],
            }],
        }],
    }],
    isClosable:  false,
    reorderEnabled:  true,
    title:  "",
    openPopouts: [],
    maximisedItemId: null,
})
