export default (appsStore, defaultCrypto, defaultCryptoAmount) => ({
    "settings": {
        "hasHeaders": true,
        "constrainDragToContainer": false,
        "reorderEnabled": true,
        "selectionEnabled": false,
        "popoutWholeStack": false,
        "blockedPopoutsThrowError": true,
        "closePopoutsOnUnload": true,
        "showPopoutIcon": false,
        "showMaximiseIcon": true,
        "showCloseIcon": false,
        "responsiveMode": "onload",
        "tabOverlapAllowance": 0,
        "reorderOnTabMenuClick": true,
        "tabControlOffset": 10,
    },
    "dimensions": {
        "borderWidth": 5,
        "borderGrabWidth": 15,
        "minItemHeight": 10,
        "minItemWidth": 10,
        "headerHeight": 20,
        "dragProxyWidth": 300,
        "dragProxyHeight": 200,
    },
    "labels": {
        "close": "close",
        "maximise": `Pay-Per-Use: 1 App Store Credit (Or use App for FREE if you have more than [${defaultCryptoAmount} ${defaultCrypto}])`,
        "minimise": "minimise",
        "popout": "open in new window",
        "popin": "pop in",
        "tabDropdown": "additional tabs",
    },
    "content": [{
        "type": "column",
        "isClosable": true,
        "reorderEnabled": true,
        "title": "",
        "content": [{
            "type": "row",
            "isClosable": true,
            "reorderEnabled": true,
            "title": "",
            "height": 94.375,
            "content": [{
                    "type": "column",
                    "isClosable": true,
                    "reorderEnabled": true,
                    "title": "",
                    "width": 31.755044737922578,
                    "content": [{
                        "type": "stack",
                        "header": {},
                        "isClosable": true,
                        "reorderEnabled": true,
                        "title": "",
                        "activeItemIndex": 0,
                        "height": 50,
                        "content": [{
                            "title": "Crypto News (Blockfolio)",
                            "type": "component",
                            "component": "Iframe",
                            "props": {
                                "name": "Crypto News (Blockfolio)",
                                "url": "https://bct-cryptonews.app.cgblockchain.com/",
                                "appId": "d3d1f856-55c8-4fed-b92e-6e572b0fcb8e",
                                appsStore,
                            },
                            "componentState": {},
                            "componentName": "lm-react-component",
                            "isClosable": true,
                            "reorderEnabled": true,
                        }],
                    }],
            }, {
                "type": "column",
                "isClosable": true,
                "reorderEnabled": true,
                "title": "",
                "width": 34.80220826113909,
                "content": [
                //     {
                //     "type": "stack",
                //     "header": {},
                //     "isClosable": true,
                //     "reorderEnabled": true,
                //     "title": "",
                //     "activeItemIndex": 0,
                //     "width": 34.831748970199236,
                //     "height": 50,
                //     "content": [{
                //         "title": "Coins Calendar",
                //         "type": "component",
                //         "component": "Iframe",
                //         "props": {
                //             "name": "Coins Calendar",
                //             "url": "https://calendar.app.cgblockchain.com/agenda/",
                //             "appId": "f3b10ab9-3212-4d19-9412-f4494c2c6dcb",
                //             appsStore,
                //         },
                //         "componentState": {},
                //         "componentName": "lm-react-component",
                //         "isClosable": true,
                //         "reorderEnabled": true,
                //     }],
                // },
                    {
                    "type": "stack",
                    "header": {},
                    "isClosable": true,
                    "reorderEnabled": true,
                    "title": "",
                    "activeItemIndex": 0,
                    "height": 50,
                    "content": [{
                        "title": "News",
                        "type": "component",
                        "component": "Iframe",
                        "props": {
                            "name": "News",
                            "url": "https://bctnews.app.cgblockchain.com/",
                            "appId": "0a1e3c26-c1b8-4d29-8b07-191be68aa8db",
                            appsStore,
                        },
                        "componentState": {},
                        "componentName": "lm-react-component",
                        "isClosable": true,
                        "reorderEnabled": true,
                    }],
                }],
            },
            {
                "type": "column",
                "isClosable": true,
                "reorderEnabled": true,
                "title": "",
                "width": 33.44274700093835,
                "content": [{
                    "type": "stack",
                    "header": {},
                    "isClosable": true,
                    "reorderEnabled": true,
                    "title": "",
                    "activeItemIndex": 0,
                    "width": 32.683655161732624,
                    "height": 50,
                    "content": [{
                        "title": "SEC News",
                        "type": "component",
                        "component": "Iframe",
                        "props": {
                            "name": "SEC News",
                            "url": "https://bct-secgov.app.cgblockchain.com/",
                            "appId": "99f4252d-e026-4868-bd16-15e99df4ae1c",
                            appsStore,
                        },
                        "componentState": {},
                        "componentName": "lm-react-component",
                        "isClosable": true,
                        "reorderEnabled": true,
                    }],
                }, {
                    "type": "stack",
                    "header": {},
                    "isClosable": true,
                    "reorderEnabled": true,
                    "title": "",
                    "activeItemIndex": 0,
                    "height": 50,
                    "content": [{
                        "title": "Telegram Messages",
                        "type": "component",
                        "component": "Iframe",
                        "props": {
                            "name": "Telegram Messages",
                            "url": "https://bct-telegram.app.cgblockchain.com/",
                            "appId": "6e4cff64-6191-4997-888f-508542825183",
                            appsStore,
                        },
                        "componentState": {},
                        "componentName": "lm-react-component",
                        "isClosable": true,
                        "reorderEnabled": true,
                    }],
                }],
            }],
        }],
    }],
    "isClosable": true,
    "reorderEnabled": true,
    "title": "",
    "openPopouts": [],
    "maximisedItemId": null,
})
