export default (appsStore, defaultCrypto, defaultCryptoAmount) => ({
    "settings": {
        "hasHeaders": true,
        "constrainDragToContainer": false,
        "reorderEnabled": true,
        "selectionEnabled": false,
        "popoutWholeStack": false,
        "blockedPopoutsThrowError": true,
        "closePopoutsOnUnload": true,
        "showPopoutIcon": false,
        "showMaximiseIcon": true,
        "showCloseIcon": false,
        "responsiveMode": "onload",
        "tabOverlapAllowance": 0,
        "reorderOnTabMenuClick": true,
        "tabControlOffset": 10,
    },
    "dimensions": {
        "borderWidth": 5,
        "borderGrabWidth": 15,
        "minItemHeight": 10,
        "minItemWidth": 10,
        "headerHeight": 20,
        "dragProxyWidth": 300,
        "dragProxyHeight": 200,
    },
    "labels": {
        "close": "close",
        "maximise": `Pay-Per-Use: 1 App Store Credit (Or use App for FREE if you have more than [${defaultCryptoAmount} ${defaultCrypto}])`,
        "minimise": "minimise",
        "popout": "open in new window",
        "popin": "pop in",
        "tabDropdown": "additional tabs",
    },
    "content": [{
        "type": "column",
        "isClosable": true,
        "reorderEnabled": true,
        "title": "",
        "content": [{
            "type": "row",
            "isClosable": true,
            "reorderEnabled": true,
            "title": "",
            "height": 94.375,
            "content": [{
                    "type": "column",
                    "isClosable": true,
                    "reorderEnabled": true,
                    "title": "",
                    "width": 31.755044737922578,
                    "content": [{
                        "type": "stack",
                        "header": {},
                        "isClosable": true,
                        "reorderEnabled": true,
                        "title": "",
                        "activeItemIndex": 0,
                        "height": 50,
                        "content": [{
                            "title": "Cryptomarketcap Info",
                            "type": "component",
                            "component": "Iframe",
                            "props": {
                                "name": "Cryptomarketcap Info",
                                "url": "https://bct-cryptomarketcap.app.cgblockchain.com/",
                                "appId": "140c9cad-95e3-411c-9798-9b145cf5e781",
                                appsStore,
                            },
                            "componentState": {},
                            "componentName": "lm-react-component",
                            "isClosable": true,
                            "reorderEnabled": true,
                        }],
                    }],
            },
            {
                "type": "column",
                "isClosable": true,
                "reorderEnabled": true,
                "title": "",
                "width": 33.44274700093835,
                "content": [{
                    "type": "stack",
                    "header": {},
                    "isClosable": true,
                    "reorderEnabled": true,
                    "title": "",
                    "activeItemIndex": 0,
                    "width": 32.683655161732624,
                    "height": 50,
                    "content": [{
                        "title": "Sunbase Stats",
                        "type": "component",
                        "component": "Iframe",
                        "props": {
                            "name": "Sunbase Stats",
                            "url": "https://bct-apps-sandbox.app.cgblockchain.com/cashflow/",
                            "appId": "645978ea-b2de-4e5c-9e0f-c0d19a5e060c",
                            appsStore,
                        },
                        "componentState": {},
                        "componentName": "lm-react-component",
                        "isClosable": true,
                        "reorderEnabled": true,
                    }],
                }, {
                    "type": "stack",
                    "header": {},
                    "isClosable": true,
                    "reorderEnabled": true,
                    "title": "",
                    "activeItemIndex": 0,
                    "height": 50,
                    "content": [{
                        "title": "Spreadsheets",
                        "type": "component",
                        "component": "Iframe",
                        "props": {
                            "name": "Spreadsheets",
                            "url": "https://bct-sheet.app.cgblockchain.com/",
                            "appId": "ccb98653-c7b3-4c0f-8459-187862566bcb",
                            appsStore,
                        },
                        "componentState": {},
                        "componentName": "lm-react-component",
                        "isClosable": true,
                        "reorderEnabled": true,
                    }],
                }],
            }],
        }],
    }],
    "isClosable": true,
    "reorderEnabled": true,
    "title": "",
    "openPopouts": [],
    "maximisedItemId": null,
})
