export default [
    {
        name: 'Binance',
        icon: 'binance.png',
        location: 'Malta',
        link: 'https://www.binance.com/en',
        status: 'active',
    },
    {
        name: 'Bitfinex',
        icon: 'bitfinex.png',
        location: 'British Virgin Islands',
        link: 'https://www.bitfinex.com/',
        status: 'active',
    },
    {
        name: 'Bitstamp',
        icon: 'bitstamp.png',
        location: 'United Kingdom',
        link: 'https://www.bitstamp.net/',
        status: 'active',
    },
    {
        name: 'Bittrex',
        icon: 'bittrex.png',
        location: 'United States of America',
        link: 'https://international.bittrex.com/',
        status: 'active',
    },
    {
        name: 'Bleutrade',
        icon: 'bleutrade.png',
        location: 'Brazil',
        link: 'https://malta.bleutrade.com/',
        status: 'active',
    },
    {
        name: 'CEX.io',
        icon: 'cex.io.png',
        location: 'United Kingdom',
        link: 'https://cex.io/',
        status: 'active',
    },
    {
        name: 'CoinbasePro',
        icon: 'coinbase.png',
        location: 'United States of America',
        link: 'https://www.coinbase.com/',
        status: 'active',
    },
    {
        name: 'Coinone',
        icon: 'coinone.png',
        location: 'South Korea',
        link: 'https://coinone.co.kr',
        status: 'active',
    },
    {
        name: 'Ethfinex',
        icon: 'ethfinex.png',
        location: 'British Virgin Islands',
        link: 'https://www.ethfinex.com/',
        status: 'active',
    },
    {
        name: 'HitBTC',
        icon: 'hitbtc.png',
        location: 'United Kingdom',
        link: 'https://hitbtc.com',
        status: 'active',
    },
    {
        name: 'HuobiPRO',
        icon: 'huobipro.png',
        location: 'Seychelles',
        link: 'https://www.hbg.com/',
        status: 'active',
    },
    {
        name: 'Kraken',
        icon: 'kraken.png',
        location: 'United States of America',
        link: 'https://www.kraken.com/',
        status: 'active',
    },
    {
        name: 'OkCoin',
        icon: 'okcoin.png',
        location: 'China',
        link: 'https://www.okcoin.com/',
        status: 'active',
    },
    {
        name: 'Poloniex',
        icon: 'poloniex.png',
        location: 'United States of America',
        link: 'https://poloniex.com/',
        status: 'active',
    },
    {
        name: 'CODEX',
        icon: 'codex.png',
        location: 'Estonia',
        link: 'https://codex.one/',
        status: 'active',
    },
    {
        name: 'IQFinex',
        icon: 'iqfinex.png',
        location: 'Switzerland',
        link: 'https://www.iqfinex.com/',
        status: 'active',
    },
    {
        name: 'P2PB2B',
        icon: 'p2pb2b.png',
        location: 'Estonia',
        link: 'https://p2pb2b.io/',
        status: 'active',
    },
    {
        name: 'CoinsBit',
        icon: 'coinsbit.png',
        location: 'Estonia',
        link: 'https://coinsbit.io',
        status: 'active',
    },
    {
        name: 'Bitkub',
        icon: 'bitkub.png',
        location: 'Thailand',
        link: 'https://www.bitkub.com/',
        status: 'active',
    },
    {
        name: 'CoinPulse',
        icon: 'coinpulse.png',
        location: 'Panama',
        link: 'https://www.coinpulse.io',
        status: 'active',
    },
    {
        name: 'EtherMium',
        icon: 'ethermium.png',
        location: 'Unknown',
        link: 'https://ethermium.com',
        status: 'active',
    },
    {
        name: 'Remitano',
        icon: 'remitano.png',
        location: 'Seychelles',
        link: 'https://remitano.com',
        status: 'active',
    },
    {
        name: 'BitBay',
        icon: 'bitbay.png',
        location: 'Poland',
        link: 'https://auth.bitbay.net',
        status: 'active',
    },
    {
        name: 'CoinEx',
        icon: 'coinex.png',
        location: 'Unknown',
        link: 'https://www.coinex.com/',
        status: 'active',
    },
    {
        name: 'Tidex',
        icon: 'tidex.png',
        location: 'United Kingdom',
        link: 'https://tidex.com/',
        status: 'active',
    },
    {
        name: 'Bitlish',
        icon: 'bitlish.png',
        location: 'United Kingdom',
        link: 'https://bitlish.com/',
        status: 'active',
    },
    {
        name: 'iCoinbay',
        icon: 'icoinbay.png',
        location: 'Republic of the Marshall Islands',
        link: 'https://www.icoinbay.com/',
        status: 'active',
    },
    {
        name: 'CoinTiger',
        icon: 'cointiger.png',
        location: 'China',
        link: 'https://www.cointiger.com',
        status: 'active',
    },
    {
        name: 'Hikenex',
        icon: 'hikenex.png',
        location: 'Malaysia',
        link: 'https://hikenex.com/',
        status: 'active',
    },
    {
        name: 'GNEISS',
        icon: 'gneiss.png',
        location: 'British Virgin Islands',
        link: 'https://gneiss.io/',
        status: 'active',
    },
    {
        name: 'Bibox',
        icon: 'bibox.png',
        location: 'China',
        link: 'https://www.bibox.com/',
        status: 'active',
    },
    {
        name: 'N.exchange',
        icon: 'n.exchange.png',
        location: 'England',
        link: 'https://n.exchange/',
        status: 'active',
    },
    {
        name: 'WavesDEX',
        icon: 'wavesdex.png',
        location: 'Decentralized Exchange',
        link: 'https://wavesplatform.com/',
        status: 'active',
    },
    {
        name: 'Exmo',
        icon: 'exmo.png',
        location: 'England',
        link: 'https://exmo.com',
        status: 'active',
    },
    {
        name: 'Bisq',
        icon: 'bisq.png',
        location: 'Decentralized Exchange',
        link: 'https://bisq.network/',
        status: 'active',
    },
    {
        name: 'ABCC',
        icon: 'abcc.png',
        location: 'Singapore',
        link: 'https://abcc.com/',
        status: 'active',
    },
    {
        name: 'Paymium',
        icon: 'paymium.png',
        location: 'France',
        link: 'https://www.paymium.com/',
        status: 'active',
    },
    {
        name: 'Bitso',
        icon: 'bitso.png',
        location: 'Mexico',
        link: 'https://bitso.com',
        status: 'active',
    },
    {
        name: 'Bluebelt',
        icon: 'bluebelt.png',
        location: 'Japan',
        link: 'https://register.bluebelt.asia/register/account-registration',
        status: 'active',
    },
    {
        name: 'LATOKEN',
        icon: 'latoken.png',
        location: 'Cayman Islands',
        link: 'https://latoken.com/',
        status: 'active',
    },
    {
        name: 'Kucoin',
        icon: 'kucoin.png',
        location: 'China',
        link: 'https://www.kucoin.com',
        status: 'active',
    },
    {
        name: 'Cryptobulls',
        icon: 'cryptobulls.png',
        location: 'Unknown',
        link: 'https://www.cryptobulls.exchange/',
        status: 'active',
    },
    {
        name: 'Zecoex',
        icon: 'zecoex.png',
        location: 'India',
        link: 'https://zecoex.com',
        status: 'active',
    },
    {
        name: 'Gatecoin',
        icon: 'gatecoin.png',
        location: 'China',
        link: 'https://gatecoin.com/',
        status: 'active',
    },
    {
        name: 'Liquid',
        icon: 'liquid.png',
        location: 'Japan',
        link: 'https://www.liquid.com/',
        status: 'active',
    },
    {
        name: 'BTCXIndia',
        icon: 'btcxindia.png',
        location: 'India',
        link: 'https://btcxindia.com/',
        status: 'active',
    },
    {
        name: 'Abucoins',
        icon: 'abucoins.png',
        location: 'Poland',
        link: 'https://abucoins.com/',
        status: 'active',
    },
    {
        name: 'Lykke',
        icon: 'lykke.png',
        location: 'Switzerland',
        link: 'https://www.lykke.com/',
        status: 'active',
    },
    {
        name: 'Coindeal',
        icon: 'coindeal.png',
        location: 'Malta',
        link: 'https://coindeal.com/',
        status: 'active',
    },

    {
        name: 'CoinCorner',
        icon: 'coincorner.png',
        location: 'United Kingdom',
        link: 'https://www.coincorner.com',
        status: 'active',
    },
    {
        name: 'Bitexbook',
        icon: 'bitexbook.png',
        location: 'Saint Vincent and the Grenadines',
        link: 'https://bitexbook.com/',
        status: 'active',
    },
    {
        name: 'Bitinfi',
        icon: 'bitinfi.png',
        location: 'China',
        link: 'https://web.bitinfi.com/',
        status: 'active',
    },
    {
        name: 'BTCTurk',
        icon: 'btcturk.png',
        location: 'Turkey',
        link: 'https://www.btcturk.com/',
        status: 'active',
    },
    {
        name: 'Kuna',
        icon: 'kuna.png',
        location: 'Ukraine',
        link: 'https://kuna.io/',
        status: 'active',
    },
    {
        name: 'MineBit',
        icon: 'minebit.png',
        location: 'South Korea',
        link: 'https://minebit.com/',
        status: 'active',
    },
    {
        name: 'Exenium',
        icon: 'exenium.png',
        location: 'Unknown',
        link: 'https://exenium.net/',
        status: 'active',
    },
    {
        name: 'CryptoExchangeWS',
        icon: 'cryptoexchangews.png',
        location: 'Italy',
        link: 'https://www.crypto-exchange.ws/',
        status: 'active',
    },
    {
        name: 'Graviex',
        icon: 'graviex.png',
        location: 'Russia',
        link: 'https://graviex.net/',
        status: 'active',
    },
    {
        name: 'Openledger',
        icon: 'openledger.png',
        location: 'Denmark',
        link: 'https://openledger.info/',
        status: 'active',
    },
    {
        name: 'BX.in.th',
        icon: 'bx.in.th.png',
        location: 'Thailand',
        link: 'https://bx.in.th/',
        status: 'active',
    },
    {
        name: 'DEx.top',
        icon: 'dex.top.png',
        location: 'Hong Kong',
        link: 'https://dex.top/',
        status: 'active',
    },
    {
        name: 'Token Store',
        icon: 'tokenstore.png',
        location: 'Decentralized Exchange',
        link: 'https://token.store/',
        status: 'active',
    },
    {
        name: 'InstantBitex',
        icon: 'instantbitex.png',
        location: 'United Kingdom',
        link: 'https://instantbitex.com/',
        status: 'active',
    },
    {
        name: 'LIQNET',
        icon: 'liqnet.png',
        location: 'Singapore',
        link: 'https://liqnet.io/',
        status: 'active',
    },
    {
        name: '3XBIT',
        icon: '3xbit.png',
        location: 'Brazil',
        link: 'https://3xbit.com.br/',
        status: 'active',
    },
    {

        name: 'NDAX',
        icon: 'ndax.png',
        location: 'Canada',
        link: 'https://ndax.io/',
        status: 'active',
    },
    {
        name: 'Coinmate',
        icon: 'coinmate.png',
        location: 'United Kingdom',
        link: 'https://coinmate.io/',
        status: 'active',
    },
    {
        name: 'Coinfloor',
        icon: 'coinfloor.png',
        location: 'United Kingdom',
        link: 'https://coinfloor.co.uk/',
        status: 'active',
    },
    {
        name: 'Vaultoro',
        icon: 'vaultoro.png',
        location: 'United Kingdom',
        link: 'https://www.vaultoro.com',
        status: 'active',
    },
    {
        name: 'Mercado Bitcoin',
        icon: 'mercadobitcoin.png',
        location: 'Brazil',
        link: 'https://www.mercadobitcoin.com.br/',
        status: 'active',
    },
    {
        name: 'Jubi',
        icon: 'jubi.png',
        location: 'China',
        link: 'https://www.jubi.com/',
        status: 'active',
    },
    {
        name: 'Coinroom',
        icon: 'coinroom.png',
        location: 'Poland',
        link: 'https://coinroom.com/',
        status: 'active',
    },
    {
        name: 'Bit-Z',
        icon: 'bit-z.png',
        location: 'United States of America',
        link: 'https://www.bit-z.com/',
        status: 'active',
    },
    {
        name: 'itBit',
        icon: 'itbit.png',
        location: 'United States of America',
        link: 'https://www.itbit.com/',
        status: 'active',
    },
    {
        name: 'BTCC',
        icon: 'btcc.png',
        location: 'China',
        link: 'https://www.btcchina.com/',
        status: 'active',
    },
    {
        name: 'Bit2C',
        icon: 'bit2c.png',
        location: 'Israel',
        link: 'https://bit2c.co.il/',
        status: 'active',
    },
    {
        name: 'Zaif',
        icon: 'zaif.png',
        location: 'Japan',
        link: 'https://zaif.jp/',
        status: 'active',
    },
    {
        name: 'CryptoX',
        icon: 'cryptox.png',
        location: 'United Kingdom',
        link: 'https://cryptox.pl/',
        status: 'active',
    },
    {
        name: 'Velox Exchange',
        icon: 'veloxexchange.png',
        location: 'United Kingdom',
        link: 'https://vlxexchange.com/',
        status: 'active',
    },
    {
        name: 'Chilebit',
        icon: 'chilebit.png',

        location: 'Chile',
        link: 'https://chilebit.net/en_US/#',
        status: 'active',
    },
    {
        name: 'IDEX',
        icon: 'idex.png',
        location: 'Decentalized Exchange',
        link: 'https://idex.market/',
        status: 'active',
    },
    {
        name: 'Braziliex',
        icon: 'braziliex.png',
        location: 'Brazil',
        link: 'https://braziliex.com/',
        status: 'active',
    },
    {
        name: 'Exrates',
        icon: 'exrates.png',
        location: 'Switzerland',
        link: 'https://exrates.me/dashboard',
        status: 'active',
    },
    {
        name: 'TuxExchange',
        icon: 'tuxexchange.png',
        location: 'Canada',
        link: 'https://tuxexchange.com/',
        status: 'active',
    },
    {
        name: 'Surbitcoin',
        icon: 'surbitcoin.png',
        location: 'Venezuela',
        link: 'https://surbitcoin.com/',
        status: 'active',
    },
    {
        name: 'CCRBX',
        icon: 'ccrbx.png',
        location: 'United Kingdom',
        link: 'https://ccrbx.io/',
        status: 'active',
    },
    {
        name: 'CoinBene',
        icon: 'coinbene.png',
        location: 'Singapore',
        link: 'https://www.coinbene.com',
        status: 'active',
    },
    {
        name: 'BTC-Alpha',
        icon: 'btc-alpha.png',
        location: 'England',
        link: 'https://btc-alpha.com/exchange/BTC_USD/',
        status: 'active',
    },
    {
        name: 'BitShares',
        icon: 'bitshares.png',
        location: 'Unknown',
        link: 'https://bitshares.org/',
        status: 'active',
    },
    {
        name: 'Gemini',
        icon: 'gemini.png',
        location: 'United States of America',
        link: 'https://gemini.com/',
        status: 'active',
    },
    {
        name: 'Coincheck',
        icon: 'coincheck.png',
        location: 'Japan',
        link: 'https://coincheck.com',
        status: 'active',
    },
    {
        name: 'BitFlip',
        icon: 'bitflip.png',
        location: 'Russia',
        link: 'https://bitflip.li/',
        status: 'active',
    },
    {
        name: 'Unocoin',
        icon: 'unocoin.png',
        location: 'India',
        link: 'https://www.unocoin.com/',
        status: 'active',
    },
    {
        name: 'NovaExchange',
        icon: 'novaexchange.png',
        location: 'Tanzania',
        link: 'https://novaexchange.com/',
        status: 'active',
    },
    {
        name: 'BitMarket',
        icon: 'bitmarket.png',
        location: 'Poland',
        link: 'https://www.bitmarket.net/',
        status: 'active',
    },
    {
        name: 'CHBTC',
        icon: 'chbtc.png',
        location: 'China',
        link: 'https://www.chbtc.com/',
        status: 'active',
    },
    {
        name: 'ViaBTC',
        icon: 'viabtc.png',
        location: 'China',
        link: 'https://www.viabtc.cn/',
        status: 'active',
    },
    {
        name: 'NERAEX',
        icon: 'neraex.png',
        location: 'Unknown',
        link: 'https://neraex.pro/',
        status: 'active',
    },
    {
        name: 'Simex',
        icon: 'simex.png',
        location: 'United States of America',
        link: 'https://simex.global/en',
        status: 'active',
    },
    {
        name: 'WEX',
        icon: 'wex.png',
        location: 'Singapore',
        link: 'https://wex.nz/',
        status: 'active',
    },
    {
        name: 'FCoin',
        icon: 'fcoin.png',
        location: 'Unknown',
        link: 'https://www.fcoin.com/',
        status: 'active',
    },
    {
        name: 'BCEX',
        icon: 'bcex.png',
        location: 'China',
        link: 'https://www.bcex.ca/',
        status: 'active',
    },
    {
        name: 'ZB',
        icon: 'zb.png',
        location: 'China',
        link: 'https://www.zb.com/',
        status: 'active',
    },
    {
        name: 'Livecoin',
        icon: 'livecoin.png',
        location: 'Belize',
        link: 'https://www.livecoin.net/',
        status: 'active',
    },
    {
        name: 'Luno',
        icon: 'luno.png',
        location: 'Singapore',
        link: 'https://www.luno.com/en/',
        status: 'active',
    },
    {
        name: 'LakeBTC',
        icon: 'lakebtc.png',
        location: 'China',
        link: 'https://www.lakebtc.com',
        status: 'active',
    },
    {
        name: 'The Rock Trading',
        icon: 'therocktrading.png',
        location: 'Italy',
        link: 'https://www.therocktrading.com/en',
        status: 'active',
    },
    {
        name: 'Huobi',
        icon: 'huobi.png',
        location: 'China',
        link: 'https://www.hbg.com/',
        status: 'active',
    },
    {
        name: 'Yunbi',
        icon: 'yunbi.png',
        location: 'China',
        link: 'https://yunbi.com/',
        status: 'active',
    },
    {
        name: 'TRUSTdex',
        icon: 'trustdex.png',
        location: 'United Kingdom',
        link: 'https://trustdex.io/',
        status: 'active',
    },
    {
        name: 'BitMEX',
        icon: 'bitmex.png',
        location: 'Republic of Seychelles',
        link: 'https://www.bitmex.com',
        status: 'active',
    },
    {
        name: 'BitGrail',
        icon: 'bitgrail.png',
        location: 'Italy',
        link: 'https://bitgrail.com/',
        status: 'active',
    },
    {
        name: 'OpenLedger',
        icon: 'openledger.png',
        location: 'Decentralized exchange',
        link: 'https://dex.openledger.io/',
        status: 'active',
    },
    {
        name: 'IncoreX',
        icon: 'incorex.png',
        location: 'Estonia',
        link: 'https://incorex.com/en/',
        status: 'active',
    },
    {
        name: 'BTC38',
        icon: 'btc38.png',
        location: 'China',
        link: 'http://www.btc38.com/',
        status: 'active',
    },
    {
        name: 'IDAX',
        icon: 'idax.png',
        location: 'Mongolia',
        link: 'https://www.idax.mn/',
        status: 'active',
    },
    {
        name: 'EXX',
        icon: 'exx.png',
        location: 'China',
        link: 'https://www.exx.com/',
        status: 'active',
    },
    {
        name: 'BTCMarkets',
        icon: 'btcmarkets.png',
        location: 'Australia',
        link: 'https://www.btcmarkets.net/',
        status: 'active',
    },
    {
        name: 'ETHEXIndia',
        icon: 'ethexindia.png',
        location: 'India',
        link: 'https://ethexindia.com/',
        status: 'active',
    },
    {
        name: 'Quoine',
        icon: 'quoine.png',
        location: 'Japan',
        link: 'https://quoine.com/',
        status: 'active',
    },
    {
        name: 'TradeSatoshi',
        icon: 'tradesatoshi.png',
        location: 'United Kingdom',
        link: 'https://tradesatoshi.com/',
        status: 'active',
    },
    {
        name: 'Bithumb',
        icon: 'bithumb.png',
        location: 'South Korea',
        link: 'https://www.bithumb.com/',
        status: 'active',
    },
    {
        name: 'bitFlyer',
        icon: 'bitflyer.png',
        location: 'Japan',
        link: 'https://bitflyer.com/ja-jp/',
        status: 'active',
    },
    {
        name: 'FoxBit',
        icon: 'foxbit.png',
        location: 'Brazil',
        link: 'https://foxbit.exchange/',
        status: 'active',
    },
    {
        name: 'Cryptopia',
        icon: 'cryptopia.png',
        location: 'New Zealand',
        link: 'https://www.cryptopia.co.nz/Exchange',
        status: 'active',
    },
    {
        name: 'LocalBitcoins',
        icon: 'localbitcoins.png',
        location: 'Finland',
        link: 'https://localbitcoins.com/',
        status: 'active',
    },
    {
        name: 'Gate.io',
        icon: 'gate.io.png',
        location: 'United States of America',
        link: 'https://gate.io/',
        status: 'active',
    },
    {
        name: 'CCEX',
        icon: 'ccex.png',
        location: 'Germany',
        link: 'https://c-cex.com',
        status: 'active',
    },
    {
        name: 'Liqui',
        icon: 'liqui.png',
        location: 'Ukraine',
        link: 'https://liqui.io/',
        status: 'active',
    },
    {
        name: 'EtherDelta',
        icon: 'etherdelta.png',
        location: 'Decentralized Exchange',
        link: 'https://etherdelta.com/',
        status: 'active',
    },
    {
        name: 'Yobit',
        icon: 'yobit.png',
        location: 'Russia',
        link: 'https://yobit.io/en/',
        status: 'active',
    },
    {
        name: 'OKEX',
        icon: 'okex.png',
        location: 'China',
        link: 'https://www.okex.com/',
        status: 'active',
    },
    {
        name: 'Catex',
        icon: 'catex.png',
        location: 'China',
        link: 'https://www.catex.io/',
        status: 'active',
    },
    {
        name: 'Yacuna',
        icon: 'yacuna.png',
        location: 'United Kingdom',
        link: 'https://yacuna.com/',
        status: 'active',
    },
    {
        name: 'BTC-Exchange',
        icon: 'btc-exchange.png',
        location: 'Lithuania',
        link: 'https://www.btc-exchange.com/',
        status: 'active',
    },
    {
        name: 'Korbit',
        icon: 'korbit.png',
        location: 'South Korea',
        link: 'https://www.korbit.co.kr/',
        status: 'active',
    },
    {
        name: 'bitFlyerFX',
        icon: 'bitflyerfx.png',
        location: 'Japan',
        link: 'https://lightning.bitflyer.jp/',
        status: 'active',
    },
    {
        name: 'CoinCap',
        icon: 'coincap.png',
        location: 'Malaysia',
        link: 'https://coincap.exchange/',
        status: 'active',
    },
    {
        name: 'VBTC',
        icon: 'vbtc.png',
        location: 'Vietnam',
        link: 'https://vbtc.exchange/',
        status: 'active',
    },
    {
        name: 'ExtStock',
        icon: 'extstock.png',
        location: 'United Kingdom',
        link: 'https://extstock.com/',
        status: 'active',
    },
    {
        name: 'Bitbank',
        icon: 'bitbank.png',
        location: 'Japan',
        link: 'https://bitbank.cc/',
        status: 'active',
    },
    {
        name: 'Aidosmarket',
        icon: 'aidosmarket.png',
        location: 'Dubai',
        link: 'https://aidosmarket.com/',
        status: 'active',
    },
    {
        name: 'DSX',
        icon: 'dsx.png',
        location: 'United Kingdom',
        link: 'https://dsx.uk/',
        status: 'active',
    },
    {
        name: 'Buda',
        icon: 'buda.png',
        location: 'Chile',
        link: 'https://www.buda.com/',
        status: 'active',
    },
    {
        name: 'CoinsBank',
        icon: 'coinsbank.png',
        location: 'United Kingdom',
        link: 'https://coinsbank.com/',
        status: 'active',
    },
    {
        name: 'UPbit',
        icon: 'upbit.png',
        location: 'South Korea',
        link: 'https://upbit.com/',
        status: 'active',
    },
    {
        name: 'BitMart',
        icon: 'bitmart.png',
        location: 'Cayman Islands',
        link: 'https://www.bitmart.com/',
        status: 'active',
    },
    {
        name: 'DDEX',
        icon: 'ddex.png',
        location: 'Cayman Islands',
        link: 'https://ddex.io/',
        status: 'active',
    },
    {
        name: 'LBank',
        icon: 'lbank.png',
        location: 'China',
        link: 'https://www.lbank.info/',
        status: 'active',
    },
    {
        name: 'SingularityX',
        icon: 'singularityx.png',
        location: 'Lithuania',
        link: 'https://exchange.singularity-x.com/',
        status: 'active',
    },
    {
        name: 'Nebula',
        icon: 'nebula.png',
        location: 'France',
        link: 'https://nebula.exchange/',
        status: 'active',
    },
    {
        name: 'RightBTC',
        icon: 'rightbtc.png',
        location: 'Dubai',
        link: 'https://www.rightbtc.com/',
        status: 'active',
    },
    {
        name: 'WorldCryptoExchange',
        icon: 'worldcryptoexchange.png',
        location: 'Malaysia',
        link: 'https://www.worldcryptocap.com/',
        status: 'active',
    },
    {
        name: 'BigONE',
        icon: 'bigone.png',
        location: 'Unknown',
        link: 'https://big.one/',
        status: 'active',
    },
    {
        name: 'Tokenomy',
        icon: 'tokenomy.png',
        location: 'Singapore',
        link: 'https://www.tokenomy.com/',
        status: 'active',
    },
    {
        name: 'Coinhub',
        icon: 'coinhub.png',
        location: 'Singapore',
        link: 'https://www.coinhub.io/en',
        status: 'active',
    },
    {
        name: 'Liquid',
        icon: 'liquid.png',
        location: 'Japan',
        link: 'https://www.liquid.com/',
        status: 'active',
    },
    {
        name: 'BTCBOX',
        icon: 'btcbox.png',
        location: 'Japan',
        link: 'https://www.btcbox.co.jp/',
        status: 'active',
    },
    {
        name: 'HADAX',
        icon: 'hadax.png',
        location: 'China',
        link: 'https://www.huobi.br.com/',
        status: 'active',
    },
    {
        name: 'Independent Reserve',
        icon: 'independentreserve.png',
        location: 'Australia',
        link: 'https://www.independentreserve.com/',
        status: 'active',
    },
    {
        name: 'Ironex',
        icon: 'ironex.png',
        location: 'Republic of China',
        link: 'https://www.ironex.exchange/',
        status: 'active',
    },
    {
        name: 'NLexch',
        icon: 'nlexch.png',
        location: 'Netherlands',
        link: 'https://www.nlexch.com/',
        status: 'active',
    },
    {
        name: 'Globitex',
        icon: 'globitex.png',
        location: 'Gibraltar',
        link: 'https://globitex.com/',
        status: 'active',
    },
    {
        name: 'ORE',
        icon: 'ore.png',
        location: 'Unknown',
        link: 'https://ore.bz/',
        status: 'active',
    },
    {
        name: 'CoinJar',
        icon: 'coinjar.png',
        location: 'England',
        link: 'https://exchange.coinjar.com/',
        status: 'active',
    },
    {
        name: 'Satang Pro',
        icon: 'satangpro.png',
        location: 'Thailand',
        link: 'https://satang.co/',
        status: 'active',
    },
    {
        name: 'Coinfalcon',
        icon: 'coinfalcon.png',
        location: 'United Kingdom',
        link: 'https://coinfalcon.com/',
        status: 'active',
    },
    {
        name: 'ACX',
        icon: 'acx.png',
        location: 'Australia',
        link: 'https://acx.io/',
        status: 'active',
    },
    {
        name: 'Bitsane',
        icon: 'bitsane.png',
        location: 'Unknown',
        link: 'https://bitsane.com/',
        status: 'active',
    },
    {
        name: 'Fisco CryptoCurrency Exchange',
        icon: 'fiscocryptocurrencyexchange.png',
        location: 'Japan',
        link: 'https://fcce.jp/',
        status: 'active',
    },
    {
        name: 'Cryptonit',
        icon: 'cryptonit.png',
        location: 'United Kingdom',
        link: 'https://www.cryptonit.net/en',
        status: 'active',
    },
    {
        name: 'BKEX',
        icon: 'bkex.png',
        location: 'British Virgin Islands',
        link: 'https://www.bkex.com/#/',
        status: 'active',
    },
    {
        name: 'BitForex',
        icon: 'bitforex.png',
        location: 'Republic of Seychelles',
        link: 'https://www.bitforex.com/',
        status: 'active',
    },
    {
        name: 'STEX',
        icon: 'stex.png',
        location: 'Unknown',
        link: 'https://www.stex.com/',
        status: 'active',
    },
    {
        name: 'Switcheo',
        icon: 'switcheo.png',
        location: 'Singapore',
        link: 'https://switcheo.network/',
        status: 'active',
    },
    {
        name: 'DigiFinex',
        icon: 'digifinex.png',
        location: 'Seychelles',
        link: 'https://www.digifinex.com/',
        status: 'active',
    },
    {
        name: 'Turtle Decentralized',
        icon: 'turtledecentralized.png',
        location: 'Belgium',
        link: 'https://www.blackturtle.eu',
        status: 'active',
    },
    {
        name: 'StocksExchange.io',
        icon: 'stocksexchange.io.png',
        location: 'England',
        link: 'https://www.stocksexchange.io/',
        status: 'active',
    },
    {
        name: 'ZBG',
        icon: 'zbg.png',
        location: 'Unknown',
        link: 'https://www.zbg.com/',
        status: 'active',
    },
    {
        name: 'Safe.Trade',
        icon: 'safe.trade.png',
        location: 'Unknown',
        link: 'https://www.safe.trade/',
        status: 'active',
    },
    {
        name: 'XS2',
        icon: 'xs2.png',
        location: 'Australia',
        link: 'https://xs2.exchange/',
        status: 'active',
    }
];
